### ISSUE TITLE
#103 breaks org-mode queries

### ISSUE THREAD

**Issue by alf-mindshift** [kostafey/ejc-sql#105]
Unfortunately, the fix made for #103 breaks queries run with `sync` set to `true`. This is used when running ejc-sql through org-babel.

The reason seems to be that the adal4j-library used to authenticate against Azure SQL seems to log some info statements before the query result is returned.

**Comment by alf-mindshift** [comment]
I've just manually reverted #103 for now, but I'll look into a proper fix to this and the other pending fixes I've promised when things are less busy at work.

**Comment by kostafey** [comment]
@alf-mindshift, could you please try the latest version of `ejc-sql` (with this commit: https://github.com/kostafey/ejc-sql/commit/f8e800df8bbbd1d6f5eec6c0524cbad07de1ef79). Are you still reproducing this bug?

**Comment by alf** [comment]
I’ve added it to my todo list. Must wait until I get back to work.

**Comment by alf-mindshift** [comment]
Can confirm that org-babel works with 0.4.0.
