### ISSUE TITLE
can't provide new instantly created tables name

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#108]
When I start a new connection to PostgreSQL, ejc-sql can provide tables name completion on existing database. But when I instantly create new tables, ejc-sql can't complete them. Can ejc-sql support this feature?

**Comment by kostafey** [comment]
ejc-sql do not interact with a database anytime autocompletion is required, it uses cache. So, the most straightforward solution is to clean the cache manually by `M-x ejc-invalidate-cache`. Then any new autocompletion request will recreate it.

But probably we should consider cleaning cache any time DDL queries successfully executed.

**Comment by stardiviner** [comment]
If it does not affect performance much, I think that's a good idea.

**Comment by stardiviner** [comment]
@kostafey Thanks for quick update, is it solved by the upper commit?

**Comment by kostafey** [comment]
@stardiviner yes, now it's fixed and described.

BTW: if you use PostgreSQL or MySQL, you can try the newest feature: ElDoc support.

**Comment by stardiviner** [comment]
@kostafey I checked out this fix, it works fine.
And the new feature ElDoc support is great!!! :+1:
I tested it works on SQL source code file, but not work on virtual Emacs buffer like dedicated opened Org source block buffer.
