### ISSUE TITLE
Cannot eval common table expression (CTE) SQL's

### ISSUE THREAD

**Issue by suryaaditya** [kostafey/ejc-sql#111]
observed we cannot eval sql's with CTE expressions, it would be helpful if you can enable as underlying driver, clojure jdbc supports the same.
eg:
```
--Define the CTE expression name and column list.  
WITH Sales_CTE (SalesPersonID, SalesOrderID, SalesYear)  
AS  
-- Define the CTE query.  
(  
    SELECT SalesPersonID, SalesOrderID, YEAR(OrderDate) AS SalesYear  
    FROM Sales.SalesOrderHeader  
    WHERE SalesPersonID IS NOT NULL  
)  
```

**Comment by kostafey** [comment]
@suryaaditya Looks like there are no problems with Clojure JDBC CTE support.
But `ejc-sql` should categorize such queries as "SELECT" query. I've fixed it.

**Comment by suryaaditya** [comment]
Got the latest code and confirm it is working now. Thanks for quick fix. ejc-sql has come a long way and it is very useful package indeed.
