### ISSUE TITLE
 (wrong-number-of-arguments (5 . 5) 1)   clomacs-ensure-nrepl-run("ejc-sql")

### ISSUE THREAD

**Issue by matteoredaelli** [kostafey/ejc-sql#112]
GNU Emacs 26.3 (build 2, x86_64-pc-linux-gnu, GTK+ Version 3.24.11)
 of 2019-09-22, modified by Debian

Th oracle jdbc is correctly installed

Below the log. I omitted the user, password and hostname of my oracle db

Debugger entered--Lisp error: (wrong-number-of-arguments (5 . 5) 1)
  clomacs-ensure-nrepl-run("ejc-sql")
  ejc-add-classpath("/home/matteo/.m2/repository/com/oracle/jdbc/ojdbc8/12.2.0.1/ojdbc8-12.2.0.1.jar")
  ejc-connect-to-db(((:classname . "oracle.jdbc.OracleDriver") (:separator . "/") (:classpath . "/home/matteo/.m2/repository/com/oracle/jdbc/ojdbc8/12.2.0.1/ojdbc8-12.2.0.1.jar") (:password . "DW_RO") (:user . "DW_RO") (:connection-uri . "jdbc:oracle:thin:@patriot.XXXXX.com:1565:PATRIOT")))
  #f(compiled-function (db connection-name) #<bytecode 0x142528d>)(((:classname . "oracle.jdbc.OracleDriver") (:separator . "/") (:classpath . "/home/matteo/.m2/repository/com/oracle/jdbc/ojdbc8/12.2.0.1/ojdbc8-12.2.0.1.jar") (:password . "XXXXX") (:user . "XXXX") (:connection-uri . "jdbc:oracle:thin:@patriot.it.pirelli.com:1565:PATRIOT")) "patriot")
  apply(#f(compiled-function (db connection-name) #<bytecode 0x142528d>) (((:classname . "oracle.jdbc.OracleDriver") (:separator . "/") (:classpath . "/home/matteo/.m2/repository/com/oracle/jdbc/ojdbc8/12.2.0.1/ojdbc8-12.2.0.1.jar") (:password . "XXX") (:user . "XXX") (:connection-uri . "jdbc:oracle:thin:@patriot.iXXXX.com:1565:PATRIOT")) "patriot"))
  #f(compiled-function (server-buff) #<bytecode 0x140411d>)(#<buffer *nrepl-server elpa/ejc-sql-20190924.1423:localhost*>)
  nrepl-server-filter(#<process nrepl-server> "nREPL server started on port 40733 on host localhost - nrepl://localhost:40733\n")

**Comment by kostafey** [comment]
Ok. What do you actually do? Could you describe steps to reproduce this bug?
Could you also provide ejc-sql version: `M-x ejc-version [RET]`

**Comment by matteoredaelli** [comment]
Hello

Now it works after deleted any files .emacs and .emacs.d/* files and reinstalling packages 

Regards
Matteo
