### ISSUE TITLE
update broke auto-completion on spacemacs-develop

### ISSUE THREAD

**Issue by pepperblue** [kostafey/ejc-sql#115]
After receiving latest package updates on spacemacs-develop auto-completion is broken:
Info from Messages-buffer is:

`Receiving database structure... [2 times]`
`Wrong type argument: stringp, nil in wrapped Clojure->Elisp function: ejc_sql.structure$complete_auto_complete@24a6df87 elisp: (ejc-complete-auto-complete "hio_base.sql" 13)`

I was trying to get more debug information with `(setq debug-on-error t)` but there was no Backtrace-buffer available ...

OS is Fedora 31
Emacs is 26.3
Spacemacs is latest on develop-branch
Java is openjdk 11.0.5
ejc-sql ist 20191125.14-43
Database is Postgresql 9.3
Driver is 42.2.8

**Comment by kostafey** [comment]
Could you please provide the Emacs Lisp stack trace (<kbd>M-x toggle-debug-on-error</kbd>) by doing the following:
1. Locate point (cursor) at the expected autocompletion position.
2. Eval desired Emacs Lisp code:
<kbd>M-:</kbd> `(ejc-complete-auto-complete "hio_base.sql" 13)`<kbd>[RET]</kbd>

The first argument here is a buffer name and the second is a current point position (can be obtained by <kbd>M-:</kbd> `(point)`<kbd>[RET]</kbd>).

**Comment by pepperblue** [comment]
It seems that auto-comlete is only broken for db-entities (tables, columns and so on). Auto-complete for SQL-keywords is working at least partially ...

**Comment by pepperblue** [comment]
Using doom-emacs and a local database-connection I get a different error with the following backtrace:
[backtrace-buffer.txt](https://github.com/kostafey/ejc-sql/files/3907128/backtrace-buffer.txt)

**Comment by kostafey** [comment]
@pepperblue, could you try the latest updated version, please.

**Comment by pepperblue** [comment]
Errors are gone! I tested against two Postgres-DBs with different results:

A remote DB with lots of tables and data (running Postgresql-Version 9.3): auto-complete is working as expected

A local DB - for testing purposes only - with only one table with two columns containing no data (running Postgresql-Version 11.6): I nearly get no candidates for table and columns in auto-complete-popup (sporadically the table is shown but never the columns)

**Comment by kostafey** [comment]
@pepperblue, please try with the current update.

**Comment by pepperblue** [comment]
For local test-DB auto-complete is working as expected now, but for remote DB auto-complete is blocking input:
[ejc-error.txt](https://github.com/kostafey/ejc-sql/files/3910847/ejc-error.txt)

**Comment by kostafey** [comment]
@pepperblue, please try the latest one.

**Comment by pepperblue** [comment]
Auto-complete now is working for me and postgres. Thank you for the fix!
