### ISSUE TITLE
Connecting to Informix-database

### ISSUE THREAD

**Issue by pepperblue** [kostafey/ejc-sql#118]
Connecting to Informix-database does not work by simply setting `:classpath` in `ejc-create-connection.` Additionally I have to add dependency in `project.clj` like `[com.ibm.informix/jdbc "4.10.13"]`.
If I want to use jdbc-driver 4.50.x I also have to add bson-dependency `[org.mongodb/bson "3.12.1"]`

**Comment by kostafey** [comment]
Unfortunately, I don't have any installed Informix databases. What version do you use? I'll try to reproduce it.

**Comment by pepperblue** [comment]
The Informix-Version is `11.70.FC8`

**Comment by kostafey** [comment]
@pepperblue, could you please remove all modifications from `project.clj`, update `ejc-sql` to the latest commit, and try to connect to the Informix database as described in https://github.com/kostafey/ejc-sql#informixconnection.

**Comment by pepperblue** [comment]
For me it's working now :+1: 
Thank you for the fix!
