### ISSUE TITLE
C-h t ejc-describe-table

### ISSUE THREAD

**Issue by holtzermann17** [kostafey/ejc-sql#121]
The readme says that <kbd>C-h t</kbd> describes a table, but it actually opens the Emacs tutorial.

Furthermore <kbd>M-x</kbd> ejc-describe-table <kbd>RET</kbd> gives an error when used with a default slot-filler.  For example:

Describe table (default quote_requests): <kbd>RET</kbd>

```
Error: ERROR: syntax error at end of input
  Position: 73
```

However, it works when I type out the name of the table:

Describe table (default quote_requests): quote_requests<kbd>RET</kbd>

**Comment by kostafey** [comment]
> The readme says that C-h t describes a table, but it actually opens the Emacs tutorial.

It's a part of `ejc-sql-mode` minor mode keymap. So, you should run `ejc-connect` first for `sql-mode` buffer or open SQL code snippet edit buffer (<kbd>C-c '</kbd> or `M-x org-edit-special`) for `org-mode` buffers.

> Furthermore M-x ejc-describe-table RET gives an error when used with a default slot-filler.

Please, provide the full error trace by enabling `M-x toggle-debug-on-error`.

**Comment by holtzermann17** [comment]
Regarding the first issue: I was running within an Org Mode buffer, so that's why the binding wasn't there. Thanks for explaining!
****
Regarding the second one: I tried just now, it's not an Emacs error -- rather, contents printed into the `*ejc-sql-output*` buffer after I press <kbd>C-c C-c</kbd>.  Is there another place to look for logs/traces?

**Comment by holtzermann17** [comment]
I ran `edebug-defun` on `ejc-describe-table` and saw that I get different inputs in the `(interactive ...)` form when I press <kbd>RET</kbd> vs when I type in the table name.

S-exp in question:
```
(ejc-get-prompt-symbol-under-point "Describe table")
```
Accept default:
> Result: (nil "js--tmp-location")

vs type out the table name:

> Result: (nil "used_asset_transactions")

**Comment by kostafey** [comment]
@holtzermann17 Please, try the latest commit.

**Comment by holtzermann17** [comment]
**Version: ejc-sql-20200204.1415**

`used_asset_transactions`<- <kbd>M-x</kbd> ejc-describe-table <kbd>RET</kbd>
```
Error: ERROR: syntax error at or near "-"
  Position: 40
```

**Comment by kostafey** [comment]
@holtzermann17 Please try the latest one.

**Comment by kostafey** [comment]
@holtzermann17, can I consider the issue closed?

**Comment by holtzermann17** [comment]
At the moment I am seeing another error.

```
Wrong number of arguments: #[nil "\306 \210\307\310\311\312\313\211\314!!\310\307\211!#\210\315\316\317!\207" [truncate-lines major-mode mode-name ejc-result-table-impl view-read-only font-lock-defaults kill-all-local-variables t ejc-result-mode "SQL-Result" case orgtbl-mode 1 (ejc-result-font-lock-keywords) run-hooks ejc-result-mode-hook] 6 nil nil], 1
  in wrapped Clojure->Elisp function: ejc_sql.connect$complete_query@3a389163
  elisp: (ejc-complete-query nil :start-time nil :status nil :display-result t :mode 'ejc-result-mode :connection-name "PO1" :db '((:classpath . "/home/joe/.m2/repository/postgresql/postgresql/9.3-1102.jdbc41/postgresql-9.3-1102.jdbc41.jar")(:password . "exchange_development")(:user . "exchange_service")(:host . "localhost")(:dbname . "openmarkets_development")(:dbtype . "postgresql")) :goto-symbol nil)
```

*****
It seems to be linked to this form inside `ejc-show-last-result`.

```
      (when mode
        (ejc-update-modes-ring mode)
        (funcall mode))
```

**Comment by kostafey** [comment]
@holtzermann17, Unfortunately, I can't reproduce your error. Please, check whether you can evaluate this code snippet after run <kbd>M-x toggle-debug-on-error</kbd>:
```clojure
(ejc-complete-query
 nil
 :start-time nil
 :status nil
 :display-result t
 :mode 'ejc-result-mode
 :connection-name "PO1"
 :db '((:classpath . "/home/joe/.m2/repository/postgresql/postgresql/9.3-1102.jdbc41/postgresql-9.3-1102.jdbc41.jar")
       (:password . "secret")
       (:user . "exchange_service")
       (:host . "localhost")
       (:dbname . "openmarkets_development")
       (:dbtype . "postgresql"))
 :goto-symbol nil)
```
Furthermore, please provide the contents of `ejc-result-mode-hook` variable.
Also, you can try to rebuild packages, probably this can help: https://github.com/kostafey/ejc-sql/issues/117#issuecomment-581959519

**Comment by holtzermann17** [comment]
I reinstalled and it is working now. Thanks!
