### ISSUE TITLE
Connection to Hive 

### ISSUE THREAD

**Issue by sshantt** [kostafey/ejc-sql#122]
I'm trying to connect to a Hive2 database and am getting the following error even though I have a valid driver linked within the classpath

`Debugger entered--Lisp error: (error "SQLException No suitable driver found for hive2://`

**Comment by pepperblue** [comment]
I have a similar issue connecting to Informix. My - hopefully - temporary solution is, to add the driver dependency to `project.clj`-file. Therefore I clone this repo locally, apply the change to `project.clj` and use the local repo within emacs - for details: #118

**Comment by sshantt** [comment]
Hey @pepperblue Thanks for the reply. Can you clarify how I can do this. How do I add my jar file driver to the dependencies list?

**Comment by pepperblue** [comment]
@sshantt I have no experience connecting to Hive, but my suggestion is to go to https://mvnrepository.com/artifact/org.apache.hive/hive-jdbc
choose one of the latest releases of the jdbc-Driver and add the listet compile dependencies - version "1.1.0" is from 2015 ...

**Comment by sshantt** [comment]
@pepperblue I tried all versions with no avail. I did get Presto working with your method though :) 

@kostafey After each successful query I get the following in my minibuffer. Any idea how to stop it from doing so?

```
Symbol’s function definition is void: :done
  in wrapped Clojure->Elisp function: ejc_sql.connect$complete_query@7664b673
  elisp: (ejc-complete-query nil :start-time '(24205 5686 724124 0 ) :status :done :display-result t :mode 'ejc-result-mode :connection-name nil :db nil :goto-symbol nil)
```

**Comment by sshantt** [comment]
Fixed the `:done` issue by following steps in issue #93

**Comment by kostafey** [comment]
@sshantt,  could you please remove all your modifications from `project.clj`, update ejc-sql to the latest commit and try to connect to the Hive database the same way as described in https://github.com/kostafey/ejc-sql#informixconnection (by using the appropriate JDBC driver artifact):
```
(ejc-create-connection
 "Hive-db-connection"
 :dependencies [[org.apache.hive/hive-jdbc "1.1.0"]]
 ...
)
```
Could you also please provide an example of a successful configured connection via `ejc-create-connection` to the Hive database (with mangled host, username, and password) to place it into the README.

**Comment by sshantt** [comment]
@kostafey I wish I could... I no longer have JDBC access to that Hive database. Its been swapped with a proprietary interface :( . Here is my successful Presto config though :) 

`
(ejc-create-connection
     "Presto-db-connection"
     :subprotocol "presto"
     :dependencies [[com.facebook.presto/presto-jdbc "0.232"]]
     :classpath "/Users/usernameHere/.m2/repository/com/facebook/presto/presto-jdbc/0.232/presto-jdbc-0.232.jar"
     :connection-uri "jdbc:presto://localhost:1234/databaseNameHere/schemaNameHere?user=databaseUserNameHere")
`

**Comment by kostafey** [comment]
@sshantt, could you please check that `:classpath` parameter is redundant here, and it works anyway. The `:dependencies` parameter is enough.

**Comment by sshantt** [comment]
@kostafey That's right the setup worked without that
```
(ejc-create-connection
     "Presto-db-connection"
     :subprotocol "presto"
     :dependencies [[com.facebook.presto/presto-jdbc "0.232"]]
     :connection-uri "jdbc:presto://localhost:1234/dbNameHere/schemaNameHere?user=dbUserNameHere")
```

**Comment by kostafey** [comment]
Fixed.
