### ISSUE TITLE
ejc-sql can't handle EXPLAIN results

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#126]
I execute following PostgreSQL EXPLAIN statement, but ejc-sql report error:

```sql
EXPLAIN SELECT rolname FROM pg_roles;
```
The error:
```
Error: A result was returned when none was expected.
```
I confirmed ejc-sql works fine. This error only happens on `EXPLAIN`.

**Comment by kostafey** [comment]
@stardiviner, please try with the latest commit.

**Comment by stardiviner** [comment]
Thanks for quick fixing. Confirmed works. :)
