### ISSUE TITLE
complete some functions for PostgreSQL is wrong

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#127]
For example, `pg_typeof` function in PostgreSQL is not shown in ejc-sql candidates. It only shown not exist function `pg_type`. Maybe my PostgreSQL driver version is old?

Also I found ejc-sql can't complete some table columns.
For example, I have a table named `cities` which has column names `city`, `temp`, `date`. But ejc-sql can't complete `city` after `SELECT`.

**Comment by stardiviner** [comment]
Gentl ping of this issue.

**Comment by kostafey** [comment]
@stardiviner, please try with the latest commit. Also, please note that column autocompletion for `SELECT` queries is restricted by a single table. E.g. this case `SELECT | FROM table` is ok, but here autocompletion will not work: `SELECT | FROM table1, table2`. 
Use aliases (or full table names) in this case:
`SELECT t1.| FROM table1 t1, table2 t2` 
or 
`SELECT table1.| FROM table1, table2`.

**Comment by stardiviner** [comment]
I tested the latest commit. It works fine now. Thanks a lot @kostafey
