### ISSUE TITLE
Cannot install in spacemacs

### ISSUE THREAD

**Issue by tutysara** [kostafey/ejc-sql#13]
I tried installing it in spacemacs by running ```M-x package-install RET ejc-sql```. I got a compilation error ```ejc-sql.el:41:1:Error: Symbol's value as variable is void: clomacs--doc``` and the package fails to install

**Comment by kostafey** [comment]
Clomacs clashes with spacemacs problem (https://github.com/clojure-emacs/clomacs/issues/8).
