### ISSUE TITLE
org table result is truncated

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#132]
I have following example:
```
#+headers: :cmdline -h localhost -p 5432 -U postgres -w
#+begin_src sql :engine postgresql
SELECT name, setting FROM pg_settings WHERE category = 'File Locations';
#+end_src

#+RESULTS[(2020-05-19 13:22:25) 2bf23da8891fcb22cbd2113da167560d16af8bdc]:
: | name              | setting                        |
: |-------------------+--------------------------------|
: | config_file       | /var/lib/postgres/data/post... |
: | data_directory    | /var/lib/postgres/data         |
: | external_pid_file |                                |
: | hba_file          | /var/lib/postgres/data/pg_h... |
: | ident_file        | /var/lib/postgres/data/pg_i... |
```
You can see, the result lines are truncated. I checked in `psql`. It's fine.
I checked all `org-table-*` prefix variables, has no option to control this truncate behavior. Then I check out `org-table.el` source code, Found some related functions `org-table-shrink`, `org-table-expand` and `org-table-toggle-column-width`. But still don't know how this behavior happend.

So I searched ejc-sql source code, found file `ejc-result-buffer.el` function `ejc-output-mode-specific-customization` invoked `org-table-align` which contains shrink table functionality. In `org-table-align`, I can't understand how it calculate this max-width.

Should this behavior controled by ejc-sql side? If yes. Then should ejc-sql add an option? or change default behavior just don't shrink table column at all? WDYT?

**Comment by kostafey** [comment]
@stardiviner, as far as I understand the essence of this issue is a column width restriction.
Looks like, you need to set `(ejc-set-column-width-limit nil)`. Also, please note, this customization should be made in `'ejc-sql-connected-hook`. Read this doc section for more details and examples:
https://github.com/kostafey/ejc-sql#performance-output-customization

**Comment by stardiviner** [comment]
Thanks a lot. I missed README. Learned new stuff. :)
