### ISSUE TITLE
mariadb no suitable driver found

### ISSUE THREAD

**Issue by schmeic** [kostafey/ejc-sql#133]
I'm correctly setting the :classpath but still get the "No suitable driver found" error when trying to connect. I've looked at issue #73 and seemed like the classpath was correct when running eval, but I didn't fully understand all the comments towards the end.

I'm using Java 11 and here are my connection parameters. Any ideas?
```elisp
(ejc-create-connection
 "test"
 :classpath (concat "~/.m2/repository/org/mariadb/jdbc/mariadb-java-client/2.6.0/"
                    "mariadb-java-client-2.6.0.jar")
 :connection-uri "jdbc:mariadb://localhost:3306/test"
 :user "test"
 :password "test")
```

**Comment by kostafey** [comment]
Could you try this one, please:
```lisp
(ejc-create-connection
 "test"
 :dependencies [[org.mariadb.jdbc/mariadb-java-client "2.6.0"]]
 :connection-uri "jdbc:mariadb://localhost:3306/test"
 :user "test"
 :password "test")
```

**Comment by schmeic** [comment]
I actually did try that first, and it did successfully install the jar file but then got the same "no suitable driver" error. I've also tried the different ways to specify db/host/port info, but that didn't help either.

Also, I do have a java project that uses the same version of the mariadb client no problem.

**Comment by kostafey** [comment]
@schmeic, the reason for this problem is missing `classname` for MariaDB in the class names map describes what class should be used with certain database type (see [clojure/java.jdbc source link](https://github.com/clojure/java.jdbc/blob/54d2339e16066aed84319c0fb5111f4b2ff22611/src/main/clojure/clojure/java/jdbc.clj#L149)). You can set it manually:
```elisp
(ejc-create-connection
 "test"
 :dependencies [[org.mariadb.jdbc/mariadb-java-client "2.6.0"]]
 :classname "org.mariadb.jdbc.Driver"
 :connection-uri "jdbc:mariadb://localhost:3306/test"
 :user "test"
 :password "test")
```

**Comment by schmeic** [comment]
That worked, thanks! Now I'm trying to figure out column completion, it's not happening for me...

**Comment by kostafey** [comment]
Yes, unfortunately at this moment `ejc-sql` doesn't support autocompletion for MariaDB (see [README](https://github.com/kostafey/ejc-sql#autocomplete)). I'll fix it on one of the weekends. If you want, you can try to implement it by yourself, even if you are not familiar with Clojure. All you need is to provide the necessary SQL queries (see [MySQL autocompletion SQL queries](https://github.com/kostafey/ejc-sql/blob/master/src/ejc_sql/structure.clj#L267) as an example).

**Comment by schmeic** [comment]
Sorry, missed that in the README. Also noticed that `ejc-show-tables-list` doesn't work, but I can run `show tables` no problem. Wouldn't the autocomplete for mariadb be exactly the same as for mysql? I've tried several of the autocompletion SQL queries from the link above in my mariadb and they all work.

**Comment by kostafey** [comment]
> Also noticed that ejc-show-tables-list doesn't work

In general, all databse-related introspection queries should be described in `ejc-sql.structure/queries` map: tables list, columns list for a table (for `autocomplete`), functions list, function parameters list (for `eldoc`), and so on and so forth.

I've added using the same database introspection queries for MariaDB as for MySQL. I can't check it at this moment, since I don't have MariaDB installed and configured, but you can try the latest commit.

**Comment by schmeic** [comment]
I just tried the latest commit, and autocomplete is now working! However, when I try and run a simple select query (that worked before), I get this error. Any ideas? 

```elisp
Debugger entered--Lisp error: (void-function case)
  (case status (:done (propertize "Done" 'face 'font-lock-keyword-face)) (:error (propertize "Error" 'face 'error)) (:terminated (propertize "Terminated" 'face 'font-lock-keyword-face)))
  (message "%s SQL query at %s. Exec time %.03f" (case status (:done (propertize "Done" 'face 'font-lock-keyword-face)) (:error (propertize "Error" 'face 'error)) (:terminated (propertize "Terminated" 'face 'font-lock-keyword-face))) (format-time-string ejc-date-output-format (current-time)) (float-time (time-since start-time)))
  ejc-message-query-done((24281 28567 813674 398000) :terminated)
```

**Comment by kostafey** [comment]
Could you restart your Emacs, please? Furthermore, what is your Emacs version?

**Comment by schmeic** [comment]
Restart didn't help. I'm using Emacs 26.3. So, to use your latest commit, I just cloned it (~/.emacs/lisp/ejc-sql) and did this:
```elisp
(add-to-list 'load-path "~/.emacs.d/lisp/ejc-sql")
(require 'ejc-sql)
```
I also removed the  melpa package to make sure I wasn't using that. Maybe my setup is not correct?

**Comment by kostafey** [comment]
It's weird. Looks like this error doesn't relate to `ejc-sql` by itself. Can you try to run <kbd>C-h f case</kbd>. Is this function exists in your Emacs?

**Comment by schmeic** [comment]
No, the case function doesn't exist. Now I've tried to revert to using the melpa package and I can't do a simple select either, but I get a different error...

**Comment by kostafey** [comment]
@schmeic, ok let's try with the latest commit. Do you have any errors at this monument?

**Comment by schmeic** [comment]
That did the trick! Working great now. One thing that I did have to add to my config was to explicitly require org otherwise I was getting orgtable-mode symbol is void. So, I just did this:

```elisp
(require 'ejc-sql)
(require 'org)
```
Thanks so much for all your help!
