### ISSUE TITLE
ejc-eval-user-sql-at-point: Symbol’s value as variable is void: db

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#137]
After upgrade on MELPA packages. new version ejc-sql has error:
```
ejc-eval-user-sql-at-point: Symbol’s value as variable is void: db
```

**Comment by kostafey** [comment]
Fixed with last commit: https://github.com/kostafey/ejc-sql/commit/15675ca3bd71e0411956e440be8d660f28ae27d8
Please, update the package.
