### ISSUE TITLE
Use with an existing Clojure programs nrepl connection

### ISSUE THREAD

**Issue by jconti** [kostafey/ejc-sql#138]
Since I am doing database development in Clojure, it would be useful to use my own program's process as the backend.  Is this possible?

**Comment by kostafey** [comment]
@jconti, please, update `ejc-sql` and it's [`clomacs`](https://github.com/clojure-emacs/clomacs) dependency and try this description in the docs: https://github.com/kostafey/ejc-sql#different-nrepl

**Comment by jconti** [comment]
Thank you!  I will try this.
