### ISSUE TITLE
ejc-sql company-mode does't auto trigger completion after "." character.

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#140]
When I connect to PostgreSQL database server, I type in `SELECT * FROM pg_catalog.` When I use `auto-complete` it works fine will auto show candidates after `.`. But when I use `company-mode`, it does not auto trigger completion after the character `.`

- ejc-sql latest version in MELPA
- company-mode latest version in MELPA

**Comment by kostafey** [comment]
`company-mode` usage still in the experimental state. But yeah, it's a bug :).

**Comment by stardiviner** [comment]
A temporary solution is set minimal prefix length of company-mode to `0`. Like this:
```elisp
(setq-local company-minimum-prefix-length 0)
```
Then it will complete after `.`. But it's a hack way.

**Comment by kostafey** [comment]
@stardiviner, please try the latest commit and set `ejc-complete-on-dot` to `t`:
https://github.com/kostafey/ejc-sql#company-mode

**Comment by stardiviner** [comment]
Thanks @kostafey , confirmed solved. 😄
