### ISSUE TITLE
After ejc-connect I see the system is listening on port 8080. Why? Can I change the port in configuration?

### ISSUE THREAD

**Issue by Voooza** [kostafey/ejc-sql#145]
Hi maintainers,
thanks for this great thing. I started using ejc-sql just recently and I especially love the integration with org-mode.

I have however run into an issue. I am working on a java application deployed to jboss and I noticed that it did not want to start.
After some digging arround I found that it is due to port 8080 being already used. 
Some more digging and I found that it happenes when I run ejc-connect. And the port gets released after ejc-quit-connection.

I was under impression that ejc-sql communicates with the backend via the nrepl connection so I am uncertain why the port 8080 is used. Can you please explain?
Also can it be configured to a different port? I would like to use ejc-sql and have my app running at the same time and I cannot easily change the port jboss is using. 

Thanks

**Comment by kostafey** [comment]
Hello, @Voooza. You can set a port by updating `clomacs-httpd-default-port` variable. Please, check this added README section:
https://github.com/kostafey/ejc-sql#set-httpd-port
furthermore, you can check out this configuration example:
https://github.com/kostafey/kostafeys-emacs-confik/blob/master/custom/ejc-sql-conf.el

**Comment by Voooza** [comment]
Awesome. thanks!
