### ISSUE TITLE
Dollar Quoting 

### ISSUE THREAD

**Issue by cbarnabas** [kostafey/ejc-sql#146]
Hello,
I am trying to run some PL/pgSQL and am getting an error regarding the dollar-quoted body. 
![2020-12-04-154137_960x1011_scrot](https://user-images.githubusercontent.com/44208860/101225926-9f697a80-3647-11eb-9f0e-e72422809920.png)

Is there some further configuration that is needed for this to execute?

**Comment by kostafey** [comment]
Hello, @cbarnabas.
1. Please, read this docs section: https://github.com/kostafey/ejc-sql#separators-delimiters
2. Please, add `:separator "/"` to the database connection configuration, e.g.: https://github.com/kostafey/ejc-sql#oracle-connection

**Comment by cbarnabas** [comment]
Ah thank you! Sorry for the noise.
