### ISSUE TITLE
[oracle structure] dba_procedures used in lieu of all_procedures 

### ISSUE THREAD

**Issue by daja93** [kostafey/ejc-sql#153]
Hello and thank you for all your work.

When trying to use your plugin, i came across the inability for me to get the DDL of a procedure (ejc could not determine the type of the object), after digging in your code, I noticed you used dba_procedures (a table over which I have do not have select right granted)

The rests of the structure.clj uses all_[*] tables, is there a particular reason for using dba for procedures ?
Thank you for your time

**Comment by kostafey** [comment]
Fixed.
