### ISSUE TITLE
direx.el no longer works after Emacs master commit d65534d254 on Dec 26 2021

### ISSUE THREAD

**Issue by mbarton98** [kostafey/ejc-sql#163]
After compiling Emacs from master, I got an error in my init file loading direx.el.

d65534d254 master * lisp/emacs-list/eieio-compat.el: Really move to obsolete

The database tree view did not work for me anyway, so I just commented out the (require 'ejc-direx) from ejc-sql.el

That allowed me to continue to use ejc-sql to connect and query my SnowFlake database from org mode. Looks like direx.el has not been updated in over six years and was relying on eieio-compat.el

**Comment by stardiviner** [comment]
I got error warning `cl-generic-ensure-function: direx:tree-name is already defined as something else than a generic function` when execute command `ejc-connect`.

**Comment by kirill-gerasimenko-da** [comment]
Got the same issue, but on installation of ejc-sql. Commenting out ejc-direx helped to get rid of this error for me.

**Comment by kostafey** [comment]
Issue fixed. Sorry for the late response. Database tree will be constructed via different tree UI.
