### ISSUE TITLE
Table in ejc-result not align correct.

### ISSUE THREAD

**Issue by cmal** [kostafey/ejc-sql#175]
In ejc-result table, wide characters (like CJK) takes 1 char wide other that 2 chars wide. Maybe this can be fixed.

Otherwise the table will not align correct when there are CJK characters in query results.

Thanks.

**Comment by cmal** [comment]
For example, in a column field whose wide is 10 characters:
1. if the query result is `me`, then there should be 8 whitespaces.
2. if the query result is `我`, then there should also be 8 whitespaces, currently it is 9.

**Comment by kostafey** [comment]
Looks fixed. @cmal, could you check it out, please.
