### ISSUE TITLE
autocomplete doesnt' work due to time out

### ISSUE THREAD

**Issue by tutysara** [kostafey/ejc-sql#18]
I am connecting to a remote sql server.
I couldn't get auto complete to work. I see this in the message buffer

```
Receiving database structure... [2 times]
Error running timer `ac-show-menu': (error "Sync nREPL request timed out (op eval session 4fda92d6-379d-4348-af0d-f7a59ad7b6e3 code (require 'ejc-sql.connect) (ejc-sql.connect/eval-sql-internal-get-column {:classname \"oracle.jdbc.OracleDriver\" :subprotocol \"oracle\" :subname \"thin:@//xxx.com\" :user \"xxx\" :password \"xxx\"} \"select DISTINCT(owner)  from ALL_OBJECTS\") id 36)")
Error running timer `ac-update-greedy': (error "Sync nREPL request timed out (op eval session 4fda92d6-379d-4348-af0d-f7a59ad7b6e3 code (require 'ejc-sql.connect) (ejc-sql.connect/eval-sql-internal-get-column {:classname \"oracle.jdbc.OracleDriver\" :subprotocol \"oracle\" :subname \"thin:@//xxx.com\" :user \"xxx\" :password \"xxx\"} \"select DISTINCT(owner)  from ALL_OBJECTS\") id 35)")

```

can we increase the timout time and make it configurable

**Comment by tutysara** [comment]
I guess we need to allow configuring ```nrepl-sync-request-timeout``` variable in clomacs

**Comment by kostafey** [comment]
User can change `nrepl-sync-request-timeout` directly, clomacs is trying to be close to CIDER as much as possible. But there are some ideas to do:

1. `nrepl-sync-request-timeout` should be mentioned in ejc-sql README.
2. Timeout should have possibility to be passed to `ejc-eval-user-sql-at-point` as prefix number, 
e.g. <kbd>M-6 M-0 C-c C-c C-c</kbd> - eval SQL with 60 sec timeout.
3. For autocomplete we should eval SQL asynchronously.

**Comment by tutysara** [comment]
most of my queries take more than a min, I had set ```nrepl-sync-request-timeout``` to 60 sec in my ```.spacemacs``` file and it works, ty.

For making autocomplete to work async, do we have anything in clomacs that support async execution?

**Comment by kostafey** [comment]
> do we have anything in clomacs that support async execution?

Not yet.

**Comment by tutysara** [comment]
ok sure, can we add this as an enhancement to clomacs. probably add a sync flag in ```clomacs-def``` args to use ```nrepl-request:eval``` and callback.

**Comment by tutysara** [comment]
Another idea is to load and cache the database structure in the clojure side and use the sync requests as usual.

**Comment by kostafey** [comment]
Database structure is already cached in EmacsLisp side. But it's an interesting idea. EmacsLisp request for database structure data can start async Clojure (probably long-running request) and receive cached data or empty data (if request still running)  immediately.

**Comment by tutysara** [comment]
Tried writing a async version of the clomacs-defun macro, here is what i have

``` lisp
;;;###autoload
(cl-defmacro clomacs-defun-async (el-func-name
                             cl-func-name
                             callback-func-name
                            &optional &key
                            (doc nil)
                            (return-type :string)
                            (return-value :value)
                            lib-name
                            namespace)
  "Wrap CL-FUNC-NAME, evaluated on clojure side by EL-FUNC-NAME.
DOC - optional elisp function docstring (when nil it constructed from
underlying clojure entity docstring if possible).
RETURN-TYPE possible values are listed in the CLOMACS-POSSIBLE-RETURN-TYPES,
or it may be a custom function (:string by default).
RETURN-VALUE may be :value or :stdout (:value by default)."
  (cl-multiple-value-bind
      (doc namespace-str cl-entity-full-name)
      (clomacs-prepare-vars cl-func-name
                            :doc doc
                            :namespace namespace)
    `(defun ,el-func-name (&rest attributes)
       ,doc
       (clomacs-ensure-nrepl-run ,lib-name)
       (let* ((attrs ""))
         (dolist (a attributes)
           (setq attrs (concat attrs " "
                               (clomacs-format-arg a))))
         (let* ((connection (clomacs-get-connection ,lib-name))
                (session (clomacs-get-session connection)))
                 (nrepl-request:eval
                  (concat
                   (if ',namespace
                       (concat "(require '" ',namespace-str ") ") "")
                   "(" ',cl-entity-full-name attrs ")")
                  (lambda (result)
                    (let* ((el-result (clomacs-get-result
                                       result ,return-value ',return-type ',namespace)))
                      (message "result %s :: el-result %s" result el-result)
                      (,callback-func-name el-result)))
                  connection
                  session))
           ))))
```
and the test code
``` lisp
(clomacs-defun-async summ-1 + (lambda (result) (message "Result: %s" result) result))
(summ-1 3 5 9)
```
does it look good?

**Comment by tutysara** [comment]
I see the changes adapted in clomacs, ty. Let me get the latest version check and see

**Comment by kostafey** [comment]
> I see the changes adapted in clomacs

That is a rough version, but feel free to play with it.

**Comment by kostafey** [comment]
Ok, looks like there is no way to prevent unwanted calls for callback except checking for result is not nil.

**Comment by tutysara** [comment]
> no way to prevent unwanted calls for callback except checking for result is not nil.

yes, nprel calls the callback for value and status update. I was looking into nrepl source code to see if they can send multiple messages with value, if they are sending multiple then we may have to collect all values till the status is done and then call the callback with the complete value.

**Comment by kostafey** [comment]
@tutysara you can test last activity about this issue in the `new-cache` branch. It will be merged to `master` branch soon after some testing.

**Comment by tutysara** [comment]
sure, let me test after office and update

**Comment by kostafey** [comment]
@tutysara `new-cache` branch merged to `master`, so the let's consider issue closed. In the case of any related bugs or ideas, new issues should be created.
