### ISSUE TITLE
Enhance README

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#19]
I don't know how to set ejc-sql for `SQLite`, `PostgreSQL` and `MySQL`.
Can you show examples in README. And add those examples in README? So that some newbie can setup by following those examples.
Thanks in advance.

**Comment by kostafey** [comment]
MySQL example is already here.

**Comment by stardiviner** [comment]
Also need to declare which clojure library needed as driver.
Does MySQL driver support MariaDB ?

**Comment by kostafey** [comment]
> Also need to declare which clojure library needed as driver.

You should use JDBC drivers the same way you use it for java. ejc-sql uses `org.clojure/java.jdbc "0.5.8"` clojure lib, a common clojure JDBC wrapper.

> Does MySQL driver support MariaDB ?

It's not a question for ejc-sql. Please search for appropriate JDBC drivers for your database via Google :)
Looks like this connector is suitable for MariaDB: https://mariadb.com/kb/en/mariadb/about-mariadb-connector-j/

**Comment by stardiviner** [comment]
Here is what got, you can consider it.

| Database             | Driver                                         |
|----------------------+------------------------------------------------|
| SQLite               | ~[sqlitejdbc "0.5.6"]~                           |
| MySQL                | ~[mysql/mysql-connector-java "5.1.6"]~           |
| MariaDB              | ~[org.mariadb.jdbc/mariadb-java-client "1.1.5"]~ |
| PostgreSQL           | ~[postgresql "9.3-1102.jdbc41"]~                 |
| Microsoft SQL Server | ~[sqljdbc4/sqljdbc4 "4.0"]~                      |

**Comment by kostafey** [comment]
Ok. Would you like me to add some notes to README for users without java & JDBC experience background?

**Comment by stardiviner** [comment]
Yes. Because I'm too.

**Comment by kostafey** [comment]
Ok, I've added a small note about JDBC installation. Please notify me, if you need more information.

**Comment by stardiviner** [comment]
I got the error when executing:
```sh
mvn org.apache.maven.plugins:maven-dependency-plugin:2.10:get -Dartifact=postgresql:postgresql:9.3-1102.jdbc41 -DrepoUrl=http://clojars.org/repo/
```

Error:
```
[ERROR] Error executing Maven.
[ERROR] 1 problem was encountered while building the effective settings
[FATAL] Non-parseable settings /home/stardiviner/.m2/settings.xml: end tag name </settings> must match start tag name <mirrors> from line 2 (position: TEXT seen ...</mirrorOf>\n    </mirror>\n</settings>... @9:12)  @ /home/stardiviner/.m2/settings.xml, line 9, column 12
```

**Comment by kostafey** [comment]
Show your `settings.xml` please.

**Comment by stardiviner** [comment]
Sorry, I checked my `seetings.xml`, I corrected it, and commands works ok. Thanks.
