### ISSUE TITLE
MySQL SET not working

### ISSUE THREAD

**Issue by oscarvarto** [kostafey/ejc-sql#191]
I recently had ejc-sql SQL Emacs client up and running.

Now (maybe some updates have broken functionality), something like
```sql
SET @serial_number='XXXBBBCCC';
SELECT @serial_number;
```
is not working.

I am using MySQL 8.x (LTS)

**Comment by oscarvarto** [comment]
Maybe it was never supported?

**Comment by kostafey** [comment]
Yes, you are right. It was never supported until now. Please, check out the updated one.

**Comment by oscarvarto** [comment]
It worked flawlessly. I'm pretty grateful for your help. Thank you very much @kostafey !!
