### ISSUE TITLE
Enhancement - Allow nrepl clojure backend to perisit between emacs restarts and allow connecting to existing nrepl backend

### ISSUE THREAD

**Issue by tutysara** [kostafey/ejc-sql#20]
Sometimes I have to restart emacs multiple times. Is there a way to keep the ejc-sql clojure backend  alive between emacs restarts or run the backend out of emacs and connect to it from emacs, like `cider-connect`

It will save a lot of time. Also the backend is very stable and I don't have a need to restart it everytime with emacs.

**Comment by kostafey** [comment]
@tutysara, sorry for so late response. You can check `Use existing nREPL` section in README for this issue.
