### ISSUE TITLE
Add helper functions to interactively setup SQL connection

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#29]
Hope `ejc-sql` can create a universal helper function to help user setup SQL connection interactively.

For example, a command `ejc-sql-connect-to-sql`,
1. it will show the stored connections in persistent when no input yet.
2. After user input some characters like `sqlite`
3. if has match connection, then select it to connect.
4. if has no match connection, then create a new connect with the inputted string.
5. then interactively prompt user to input parameters of the connection, even auto show the available SQL JDBC drivers in available possible paths like `~/.m2/`.

**Comment by kostafey** [comment]
Note: related pull request https://github.com/kostafey/ejc-sql/pull/84 (rejected but contains useful conversation).

**Comment by kostafey** [comment]
@stardiviner, Ok looks like the feature is implemented. 
See description in README: https://github.com/kostafey/ejc-sql#interactive-connection-creation
I hope that the creation process is simple enough that the user can be not familiar with Java & JDBC to configure a connection. The required JDBC driver will be automatically resolved and downloaded (if not yet) for the selected database type. Manual installation is not required for interactive-configured connections.

**Comment by stardiviner** [comment]
This is awesome!!! Thanks @kostafey. Much better than my simple and rough implementation.

**Comment by stardiviner** [comment]
This is awesome!!! Thanks @kostafey. Much better than my simple and rough implementation.
