### ISSUE TITLE
Use configurable keymap prefix

### ISSUE THREAD

**Issue by nigredo-tori** [kostafey/ejc-sql#31]
Current keybindings are short and will probably clash with some pre-existing ones (most notably, `C-c p` is used by projectile). This can be resolved on case-by-case basis, but it's probably worth it to provide a configurable keymap prefix. Here's how projectile does it: https://github.com/bbatsov/projectile/blob/da581cdfe4f4f63137f3320ed3dbda9cf6c20e14/projectile.el#L3469-L3523

**Comment by kostafey** [comment]
Ok. I've added prefix key for some bindings. But what about keeping some keys as-is? 
https://github.com/kostafey/ejc-sql/blob/master/ejc-sql.el#L64

- `C-c C-c` - is too common to eval something.
- `C-h ...` - to pretend common emacs help keys.
- `C-s-<arrows>` - keys are too handy. I haven't seen any clashes with them.

**Comment by nigredo-tori** [comment]
I've only seen `C-c C-c` being used for compilation, but eval is close enough.
`C-h t` clashes with Emacs tutorial of all things, but shouldn't be a problem. It would be a bit more intuitive for me if this was something like `C-c C-v t` though, to keep it aligned with Ensime bindings, but that's just me.

About `C-s-<arrows>` - `Super` is often used by something system-wide. In vanilla Ubuntu environment, for instance, these maximize and minimize windows. What about `C-M-n/p` instead? They seem to be standard for navigation (`forward-sexp`, for example).

**Comment by nigredo-tori** [comment]
Sorry, I meant `C-M-f/b` in the last paragraph.

**Comment by kostafey** [comment]
Oh, really I've forgotten about `C-h t` for Emacs tutorial. `C-s-<arrows>` are replaced with `C-M-f/b`. Can I consider the issue closed?

**Comment by nigredo-tori** [comment]
Yes, it's fixed. Thank you.
