### ISSUE TITLE
Oracle 11.2.0.4 invalid character (ORA-00911) for ejc-show-tables-list

### ISSUE THREAD

**Issue by peterjasc** [kostafey/ejc-sql#32]
invalid character (ORA-00911) for ejc-show-tables-list

**Comment by kostafey** [comment]
What is database type? Could you show the full stack trace, please?

**Comment by peterjasc** [comment]
Oracle 11.2.0.4

Stack trace:

Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  get-buffer(nil)
  display-buffer(nil)
  sql-show-sqli-buffer()
  funcall-interactively(sql-show-sqli-buffer)
  call-interactively(sql-show-sqli-buffer nil nil)
  command-execute(sql-show-sqli-buffer)

**Comment by kostafey** [comment]
@peterjasc, could you update `ejc-sql` and [clomacs](https://github.com/clojure-emacs/clomacs) and checkout `ejc-show-tables-list` again, please?

**Comment by peterjasc** [comment]
@kostafey 
Debugger entered--Lisp error: (error "Run M-x ejc-connect first!")
  signal(error ("Run M-x ejc-connect first!"))
  error("Run M-x ejc-connect first!")
  ejc-check-connection()
  ejc-show-tables-list()
  funcall-interactively(ejc-show-tables-list)
  call-interactively(ejc-show-tables-list record nil)
  command-execute(ejc-show-tables-list record)
  execute-extended-command(nil "ejc-show-tables-list" "ejc-show-ta")
  funcall-interactively(execute-extended-command nil "ejc-show-tables-list" "ejc-show-ta")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by peterjasc** [comment]
@kostafey **nil**, no errors

**Comment by kostafey** [comment]
I've added current schema receiving for Oracle but, unfortunately, I don't have running Oracle db instance to check the result. You can update `ejc-sql` and try to get `ejc-show-tables-list` again. If no luck, please, provide the correct way to receive actual db schema.

**Comment by peterjasc** [comment]
@kostafey as soon as I have time.

Debugger entered--Lisp error: (error "SQLSyntaxErrorException ORA-00911: invalid character\n  oracle.jdbc.driver.T4CTTIoer.processError (T4CTTIoer.java:447)\n")
  signal(error ("SQLSyntaxErrorException ORA-00911: invalid character\n  oracle.jdbc.driver.T4CTTIoer.processError (T4CTTIoer.java:447)\n"))
  error("SQLSyntaxErrorException ORA-00911: invalid character\n  oracle.jdbc.driver.T4CTTIoer.processError (T4CTTIoer.java:447)\n")
  clomacs-get-result((dict "status" ("eval-error" "done") "id" "20" "ns" "user" "session" "6b03c75f-3ec9-4758-860b-e7f7da4c0960" "value" "nil" "ex" "class java.sql.SQLSyntaxErrorException" "root-ex" "class java.sql.SQLSyntaxErrorException" "err" "SQLSyntaxErrorException ORA-00911: invalid character\n  oracle.jdbc.driver.T4CTTIoer.processError (T4CTTIoer.java:447)\n") :value :string ejc-sql\.structure)
  ejc-select-db-meta-script(((:classpath . "/home/peter/.m2/repository/com/oracle/jdbc/ojdbc6/11.2.0.4/ojdbc6-11.2.0.4.jar") (:classname . "oracle.jdbc.driver.OracleDriver") (:subprotocol . "oracle") (:subname . "thin:@ldap://tnsldap.int.hansa.ee/dev_ee_core,cn=OracleContext,dc=int,dc=ora,dc=sbcore,dc=net") (:user . "vpaber") (:password . "vpaberv") (:separator . "/")) :tables :owner nil)
  ejc-show-tables-list()
  funcall-interactively(ejc-show-tables-list)
  call-interactively(ejc-show-tables-list record nil)
  command-execute(ejc-show-tables-list record)
  execute-extended-command(nil "ejc-show-tables-list" "ejc-show-tab")
  funcall-interactively(execute-extended-command nil "ejc-show-tables-list" "ejc-show-tab")
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)

**Comment by kostafey** [comment]
Looks fixed now. Please check the last version.
