### ISSUE TITLE
C-c e t seems to include tables only from dbo schema for MS Sql Server

### ISSUE THREAD

**Issue by kirill-gerasimenko** [kostafey/ejc-sql#35]
Hi,

When I do `C-c e t` the returned list of tables in the database has only tables from `dbo` schema. 
I'm using Sql Server 2016.
I can track it till (def default-queries ..) where `:tables` gets set, and it is used later for ms sql, and the `schema` there is `dbo` in my case (checked with profiler) which filters out everything other than `dbo`, but can't figure out further :)

**Comment by kostafey** [comment]
That is an expected behaviour, to get tables list for current DB schema:
https://github.com/kostafey/ejc-sql/blob/master/src/ejc_sql/structure.clj#L234

Would you like to see the full tables list?

**Comment by kirill-gerasimenko** [comment]
Yes, that would be helpful, since we practice grouping tables under certain schema, and to quickly look at the tables list to find out the name helps a lot. 

Also a bit related thing - autocomplete for custom schema seems not to work:
```
select
*
from
customschema.
```
After final `.`  nothing appears. 
I can create another issue for the latter if you wish.

**Comment by kirill-gerasimenko** [comment]
May be pass parameter with `C-u` to the command so it shows tables from all schemas?

**Comment by kirill-gerasimenko** [comment]
Hi,

For SQL server this gives me error because of `LCASE` function, seems like for TSQL it's equivalent is `LOWER` 
(https://docs.microsoft.com/en-us/sql/t-sql/functions/lower-transact-sql).

`Error: 'LCASE' is not a recognized built-in function name.`

Thanks a lot, these changes you make make my use cases easier!

**Comment by kostafey** [comment]
To figure out the problem of tables autocomplete for custom schema, could you check the result of this query:
```sql
SELECT table_name                 
FROM information_schema.tables    
WHERE table_schema = 'customschema'
ORDER BY table_name
```

**Comment by kirill-gerasimenko** [comment]
This gives empty result set.

**Comment by kostafey** [comment]
Ok, and what returns the following snippet:
```sql
SELECT t.table_name
FROM information_schema.schemata AS s,            
     information_schema.tables AS t               
WHERE t.table_schema = s.schema_name              
  AND s.schema_owner = 'customschema'
```

**Comment by kirill-gerasimenko** [comment]
The same - empty result set.

**Comment by kostafey** [comment]
Ok, this one:
```sql
SELECT t.name 
FROM sys.tables AS t
INNER JOIN sys.schemas AS s
  ON t.schema_id = s.schema_id
WHERE s.name = 'customschema'
```

**Comment by kirill-gerasimenko** [comment]
Nope :) Still nothing

**Comment by kostafey** [comment]
This is weird. For me, all these cases provide correct tables list. Do you bundle tables to 'customschema' correctly? Furthermore, this can be caused by SQL Server version, since I have only older instances. Could you provide the correct query for tables list of predefined schema name, please?

**Comment by kirill-gerasimenko** [comment]
Oh, my. It seems like I missed that part with `customschema` - it was a dummy name I used as an example and I don't have it as a real schema in the database - that's why I couldn't find it, and misguided you with my answers. 

Below, I'm using now real schema `config`, this first query you asked to check gives me 5 results, which are correct for my case (table names are not relevant). I'm using SSMS to run queries. 

``` sql
SELECT table_name                 
FROM information_schema.tables    
WHERE table_schema = 'config'
ORDER BY table_name
```

The one below - gives no results:

``` sql 
SELECT t.table_name
FROM information_schema.schemata AS s,            
     information_schema.tables AS t               
WHERE t.table_schema = s.schema_name              
  AND s.schema_owner = 'config'
```
And this below - gives the same result as the first one - 5 proper table names in my case.
``` sql
SELECT t.name 
FROM sys.tables AS t
INNER JOIN sys.schemas AS s
  ON t.schema_id = s.schema_id
WHERE s.name = 'config'
```

Sorry again for the confusion, thanks for your effort on the project!

**Comment by kirill-gerasimenko** [comment]
I've forgotten to mention that for `dbo` auto-completion works correctly.

**Comment by kostafey** [comment]
@kirill-gerasimenko. looks fixed. Please, check it out.

**Comment by kirill-gerasimenko** [comment]
Looks good now, thanks!
