### ISSUE TITLE
ejc-connect-existing-repl error

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#45]
```
Debugger entered--Lisp error: (wrong-type-argument listp 46165)
  call-interactively(ejc-connect-existing-repl record nil)
  command-execute(ejc-connect-existing-repl record)
  #f(compiled-function (cmd) #<bytecode 0x28c4071>)("ejc-connect-existing-repl")
  ivy-call()
....
```

**Comment by stardiviner** [comment]
@kostafey Is there a simple way to make it work? Or can you fix it quickly. Because I use it a lot in my current programming flow. Like I open an Org Mode SQL src block, then enable `ejc-sql-mode` and connect to existing connection.

**Comment by kostafey** [comment]
Looks fixed. Please update `ejc-sql` and try again. Furthermore, please note, that new `lein` should be stared by `lein repl`.

**Comment by kostafey** [comment]
Looks fixed. Please, update `ejc-sql` and `clomacs` projects, then try again by `lein repl` and `ejc-connect-existing-repl`.

**Comment by stardiviner** [comment]
Confirmed. It works. Thanks for quick update!!!

**Comment by stardiviner** [comment]
I found `ejc-connect-existing-repl` does not bind current buffer with ejc-sql session.
Here is my steps to reproduce this issue:

```elisp
(ejc-create-connection
   "PostgreSQL"
   :classpath "~/.m2/repository/postgresql/postgresql/9.3-1102.jdbc41/postgresql-9.3-1102.jdbc41.jar"
   :dbtype "postgresql"
   :host "localhost"
   :port "5432"
   :user "postgres"
   :password "***"
   :dbname "postgres")
```

1. `[M-x ejc-connect RET PostgreSQL RET]` to launch a new ejc-sql REPL session.
2. In another Org Mode file buffer, open a sql source block like this:

```org
   #+begin_src sql :eval no
   SELECT * from test;
   #+end_src
```

3. In the opened source block dedicated buffer, I press `[C-c C-c]` on SQL statement line to eval. But it shows warning: `Run M-x ejc-connect first!`.
