### ISSUE TITLE
How about make `ejc-connect` async like CIDER start REPL?

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#54]
CIDER launch for project is async by default. `ejc-connect` takes about 1.5 minutes, it is not very long, but if async is easy, I hope it can be async.

**Comment by kostafey** [comment]
@stardiviner, could you please confirm that it's workes as expected?

**Comment by stardiviner** [comment]
@kostafey Confirmed latest async commit works for me. Awesome. This is really a big step I feel. And thanks for your work. (I saw you recently keep updating clomacs and ejc-sql in GitHub feeds.)
