### ISSUE TITLE
[C-c C-c] can't evaluate SQL statement

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#55]
Here is my steps to reproduce this issue:

```elisp
(ejc-create-connection
   "PostgreSQL"
   :classpath "~/.m2/repository/postgresql/postgresql/9.3-1102.jdbc41/postgresql-9.3-1102.jdbc41.jar"
   :dbtype "postgresql"
   :host "localhost"
   :port "5432"
   :user "postgres"
   :password "***"
   :dbname "postgres")
```

1. `[M-x ejc-connect RET PostgreSQL RET]` to launch a new ejc-sql REPL session.
2. In another Org Mode file buffer, open a sql source block like this:

```org
   ,#+begin_src sql :eval no
   SELECT * from test;
   ,#+end_src
```

3. In the opened source block dedicated buffer, I press `[C-c C-c]` on SQL statement line to eval. But it shows warning: `Run M-x ejc-connect first!`.

**Comment by kostafey** [comment]
Database-connection info is buffer-local. So, to get a possibility to eval SQL statements from
any new buffer, you should run `M-x ejc-connect` inside this buffer. No new REPL will launch in this case (if started already), it will add only database connection information. Different buffers can connect to different databases (even different database types). All connection-related data (e.g. database structure cache) shared between buffer with the same connection.

**Comment by stardiviner** [comment]
But it have to start a new REPL for every new opened source blocks everytime. This is not convinient. I also tried `ejc-connect-existing-repl`. It create a sibling REPL or something else. But it can't use `[C-c C-c]` neither. I think I only need to create one new REPL, and use `ejc-connect-existing-repl` for all new buffers.
I checked the `ejc-connect` source code, I think might can extract the set buffer local steps into a single command, so that user can set those info in any new buffer to work like `ejc-connect`.

**Comment by kostafey** [comment]
> But it have to start a new REPL for every new opened source blocks everytime.

You have not. Once again. If you connected to nREPL with `ejc-sql` project (your Emacs has buffer like `*nrepl-server...ejc-sql...*`), than any time you run `ejc-connect`, no new nREPL should be started. It will add  buffer-local vars with database-connection info to this buffer. Only. If not (and you see starting new REPL every time), this is either `ejc-sql` bug, or you are doing something unextected, so, pleace, describe it.

> I think might can extract the set buffer local steps into a single command, so that user can set those info in any new buffer to work like ejc-connect.

It's possible and rather simple. As far as I understand, you want to keep database-connection info in some `org-mode` buffer and atomaticaly copy it to any source code dedicated buffers (via `org-edit-special`). Am I right?

**Comment by stardiviner** [comment]
> As far as I understand, you want to keep database-connection info in some org-mode buffer and automatically copy it to any source code dedicated buffers (via org-edit-special). Am I right?

Yes, that's what I want.

About the `ejc-connect`. I will try again. Thanks for your explaination. This sentence is clear than upper comment.

**Comment by stardiviner** [comment]
I tested, `ejc-connect` did link to existing database-connection. This is great.

**Comment by stardiviner** [comment]
Oops, close issue by accidently.
I can use `[C-c C-c]` now, but it does not gives out result, it seems always running:

![image](https://user-images.githubusercontent.com/378699/48235019-fc59be80-e3f6-11e8-83fd-9fc7e0649d82.png)

**Comment by stardiviner** [comment]
I dive into the source code of `ejc-eval-user-sql-at-point` with edebug.
And invoke `(ejc-eval-user-sql-at-point :sync)` in buffer. It returns:
```
"{:runner #future[{:status :pending, :val nil} 0x518e1d76], :start-time (23524 55318 576661 903000), :stmt #object[com.mysql.jdbc.JDBC4PreparedStatement 0x1f1e78e7 \"com.mysql.jdbc.JDBC4PreparedStatement@1f1e78e7: statement has been closed, no further internal information available\"], :conn #object[com.mysql.jdbc.JDBC4Connection 0x64ef8c23 \"com.mysql.jdbc.JDBC4Connection@64ef8c23\"]}"
```

**Comment by stardiviner** [comment]
@kostafey Hi, any update on this issue?

**Comment by kostafey** [comment]
@stardiviner Ok, lest figure out what we expect here.
First pleace, update ejc-sql, and try with new version from master.

1. Problem - infinite evaluation run of expression:
```sql
use testdb;
show tables
```
Unfortunately, I can't reproduce it at all (tested with H2 and MySQL databases).
Any time I receive tables list as expected.
Could you confirm that problem persists for your MySQL database?

2. Use ejc-sql for block dedicated buffer from org-mode buffer.

I can offer the following behaviour:
* run `ejc-connet` in you `org-mode` buffer as in `sql-mode` buffer
* the `major-mode` for the current `org-mode` buffer persists (as `org-mode`)
* new `minor-mode` (`ejc-sql-mode`) will be added to this `org-mode` buffer
* any time you run <kbd>C-c '</kbd> (`org-edit-special`) you will get new buffer with this `minor-mode` (`ejc-sql-mode`) and all connection-related data.

Is it acceptable behaviour?

**Comment by stardiviner** [comment]
About the first problem, I tried the latest version code. I pull from your `master` branch. The latest commit is `17b633f7308d1f814eec141f46189e70effb3a5d`

**Comment by stardiviner** [comment]
About the first problem, I tried the latest version code. I pull from your `master` branch. The latest commit is `17b633f7308d1f814eec141f46189e70effb3a5d`

Here is my config:
```elisp
(use-package ejc-sql
  ;; :ensure t
  :load-path "~/Code/Emacs/ejc-sql"
  :load (ejc-interaction)
  :commands (ejc-connect ejc-connect-existing-repl ejc-sql-mode)
  :config
  (defun my-ejc-sql-ac-setup ()
    (ejc-sql-mode 1)
    (auto-complete-mode 1)
    (ejc-ac-setup))
  (add-hook 'sql-mode-hook #'my-ejc-sql-ac-setup)

  ;; (advice-add 'ejc-connect :before
  ;;             #'(lambda (connection-name)
  ;;                 (switch-to-buffer-other-window (format "*ejc-sql %s*" connection-name))))
  
  (ejc-create-connection
   "PostgreSQL-db-postgres"
   :classpath "~/.m2/repository/postgresql/postgresql/9.3-1102.jdbc41/postgresql-9.3-1102.jdbc41.jar"
   :dbtype "postgresql"
   :host "localhost"
   :port "5432"
   :user "postgres"
   :password "password"
   :dbname "postgres")

  (ejc-create-connection
   "MariaDB-db-test"
   :classpath "~/.m2/repository/org/mariadb/jdbc/mariadb-java-client/1.1.7/mariadb-java-client-1.1.7.jar"
   :dbtype "mysql" ; TODO: "mariadb"?
   :host "localhost"
   :port "3306"
   :user "root"
   :password "password"
   :dbname "test")
  
  (ejc-create-connection
   "MySQL-db-test"
   :classpath "~/.m2/repository/mysql/mysql-connector-java/5.1.32/mysql-connector-java-5.1.32.jar"
   :dbtype "mysql"
   :host "localhost"
   :port "3306"
   :user "root"
   :password "password"
   :dbname "test")
  )
```

And here is my Org file contains steps of reproducing my problem. 
I combined two "MySQL/MariaDB" and "PostgreSQL" reproduce steps into one file.
https://gist.github.com/stardiviner/7243e6c4a6ad4843304e796149f32c04


About 2:

>     Use ejc-sql for block dedicated buffer from org-mode buffer.
> 
> I can offer the following behaviour:
> 
>     run ejc-connet in you org-mode buffer as in sql-mode buffer

`in your org-mode buffer`, Do you mean the org-mode buffer, or the opened source block dedicate buffer? If `org-mode buffer`. I think it's the best. But I tested with latest code. After execute command `ejc-connect`. It still will make major mode `org-mode` into `sql-mode`.

>     the major-mode for the current org-mode buffer persists (as org-mode)
>     new minor-mode (ejc-sql-mode) will be added to this org-mode buffer
>     any time you run C-c ' (org-edit-special) you will get new buffer with this minor-mode (ejc-sql-mode) and all connection-related data.
> 
> Is it acceptable behavior?

This is what I want. That will be great!!

**Comment by kostafey** [comment]
1. Problem - infinite evaluation run of expression.
I can't reproduce it anyway, **BUT**...
I've made some investigation of it. There are 2 probable cases leads to *"infinite"* evaluation run:
* An error when Clojure calls to Elisp (to notice Emacs about the end of SQL query evaluation).
* An error in Java SQL query evaluation thread itself.

So, please update `ejc-sq` and `clomacs` packages and try again. You should never fail into
*"infinite"* evaluation run and see the **real** problem description in `minibuffer`, `*Messages*` and `*ejc-sql-output*` buffers (depends on the problem origin).

2. Problem - Use `ejc-sql` for `org-mode`.
It's implemented as discussed above. Furthermore, you can evaluate SQL queries from code snippets 
inside `org-mode` buffer directly.
For the detailed description, please read this section of the README: https://github.com/kostafey/ejc-sql#use-with-org-mode

**Comment by stardiviner** [comment]
With this latest fix commit, `[C-c C-c]` works now. Thanks for quick fix @kostafey .
