### ISSUE TITLE
No implementation of method: :as-file of protocol: #’clojure.java.io/Coercions found for class: java.lang.Boolean  clojure.core/-cache-protocol-fn 

### ISSUE THREAD

**Issue by matteoredaelli** [kostafey/ejc-sql#65]
When trying to connect to a database with "ejc-connect" I get

Starting nREPL server for ejc-sql...
[nREPL] server started on 45811
[nREPL] Establishing direct connection to localhost:45811 ...
[nREPL] Direct connection to localhost:45811 established
Started.
clomacs-get-result: IllegalArgumentException No implementation of method: :as-file of protocol: #’clojure.java.io/Coercions found for class: java.lang.Boolean  clojure.core/-cache-protocol-fn (core_deftype.clj:583)

I use debian testing linux x64
lein -v
Leiningen 2.8.1 on Java 1.8.0_171 OpenJDK 64-Bit Server VM

regards
Matteo

**Comment by kostafey** [comment]
Could you please provide you connection configuration (with mangled username and password)?

**Comment by matteoredaelli** [comment]
(ejc-create-connection
 "Oracle-patriot"
 :classpath (concat "~/.m2/repository/com/oracle/jdbc"
                     "/ojdbc8/12.1.0.2/ojdbc8-12.1.0.2.jar")
 :user "myuser"
 :password "mypwd"
 :dbtype "oracle"
 :dbname "PATRIOT"
 :host "patriot.redaelli.org"
 :port "1565"
 :separator "/")


matteo@debian:~$ ls -l ~/.m2/repository/com/oracle/jdbc/ojdbc8/12.1.0.2/ojdbc8-12.1.0.2.jar
-rw-r--r-- 1 matteo matteo 4036257 Feb 13  2018 /home/matteo/.m2/repository/com/oracle/jdbc/ojdbc8/12.1.0.2/ojdbc8-12.1.0.2.jar

**Comment by kostafey** [comment]
Looks reproduced by
```clojure
  (use '[cemerick.pomegranate :only (add-dependencies)])
  (require 'cemerick.pomegranate)
  
  (add-dependencies :coordinates '[[incanter "1.9.2"]]
                   :repositories (merge cemerick.pomegranate.aether/maven-central
                                        {"clojars" "https://clojars.org/repo"}))

(cemerick.pomegranate/add-classpath 'incanter.core) =>
```
```
1. Unhandled java.lang.IllegalArgumentException
   No implementation of method: :as-file of protocol:
   #'clojure.java.io/Coercions found for class: clojure.lang.Symbol
```

1. `project.clj`:
```
:dependencies [[org.clojure/clojure "1.10.0"]
               [com.cemerick/pomegranate "1.1.0"]]
```
2. `Leiningen 2.9.1 on Java 1.8.0_131 Java HotSpot(TM) 64-Bit Server VM`

**Comment by kostafey** [comment]
Looks dublicate https://github.com/kostafey/ejc-sql/issues/87
