### ISSUE TITLE
[Discuss] I'm wondering is it possible to support SQL keywords completion?

### ISSUE THREAD

**Issue by stardiviner** [kostafey/ejc-sql#70]
Sorry for my poor SQL knowledge.

When using MySQL connection, I found ejc-sql auto-complete can't complete `USE` keywords. Then I checked out source code, found `ac-source-ejc-ansi-sql` backend. Then directed me to variable `ejc-ansi-sql-words`. It does not contains `use`. I checked ANSI SQL reserved keywords which does not include it too.
Then I know `use` is keyword in MySQL. But I use https://www.petefreitag.com/tools/sql_reserved_words_checker/?word=use to check, it says it's not reserved keywords in MySQL. I'm confused.

Which part should provide this `USE` keyword completion?

**Comment by kostafey** [comment]
Ok. It's possible to provide database-type specific autocompletion for keywords & functions.

**Comment by stardiviner** [comment]
Great, thanks @kostafey

**Comment by stardiviner** [comment]
This is really fast! Awesome, I will try today or tomorrow soon. And thanks.

**Comment by kostafey** [comment]
@stardiviner oh, no, not yet ;). It's a simply **incomplete** attempt of one of the approaches. It's not in `master` and will be **completely** rewrited. Please, hold on :).

**Comment by stardiviner** [comment]
Oh, Aha, it's fine. :)

**Comment by kostafey** [comment]
@stardiviner ok, I've added database-specific keywords support for the following databases:
* Oracle
* PostgreSQL
* H2
It's in `master` branch now.
Please, note, you should provide access to `mysql.help_keyword` table for MySQL databases (if your db user is not `root`): https://github.com/kostafey/ejc-sql#mysqlconnection

**Comment by stardiviner** [comment]
Wow! @kostafey , I have no words to express my thanks. If could, I would buy you a beer. :)

Confirmed MySQL keywords completion.
When I test postgresql keywords completion. I got error when start postgresql connection.
```
clomacs-get-result: PSQLException Method org.postgresql.jdbc4.Jdbc4Connection.isValid(int) is not yet implemented.  org.postgresql.Driver.notImplemented (Driver.java:753)
```

**Comment by kostafey** [comment]
Ok, you run `ejc-connect` and fail with this error. Looks like it's not related to this issue. So, please:
1. Try the latest PostgreSQL JDBC driver version.
2. Open new issue.
3. Provide your connection configuration (with mangled username & password).
