### ISSUE TITLE
How do I debug?

### ISSUE THREAD

**Issue by trisrael** [kostafey/ejc-sql#72]
I've been getting this issue when attempting to connect to a PG connection:

`ejc-httpd-start: Wrong type argument: symbolp, (gensym "require")`

Whereas in older versions it worked fine, but even when I go back to them now they break.
I've went through the install steps again, and updated all my jdbc drivers but I am still getting this issue.

Do you have any suggestions on how to debug the issue? Or is there a log somewhere of the actions taken by ejc?

```
(ejc-create-connection
  "local-provider"
  :classpath (concat "~/.m2/repository/postgresql/postgresql/42.2.5.jre7/"
                     "postgresql-42.2.5.jre7.jar")
  :classname "org.postgresql.Driver"
  :subprotocol "postgresql"
  :subname "//localhost:5432/a-db-name"
 )
```

**Comment by kostafey** [comment]
Stable versions: `ejc-sql 0.2`, `clomacs 0.03`.
