### ISSUE TITLE
Version of org.apache.commons/commons-lang3 conflicts with com.microsoft.azure/adal4j 

### ISSUE THREAD

**Issue by alf-mindshift** [kostafey/ejc-sql#77]
Because I need to use the Azure Active Directory Authentication feature in sqlserver, I need to include the adal4j package as per https://docs.microsoft.com/en-us/sql/connect/jdbc/feature-dependencies-of-microsoft-jdbc-driver-for-sql-server?view=sql-server-2017. 

Unfortunately this doesn't work out of the box with ejc-sql because ejc-sql depends on an older versjon of commons-lang3 which shadows the version used by adal4j and thus causes runtime errors. I've been able to make things work by patching the project.clj file and upgrading from 3.2.1 to 3.5.

https://github.com/kostafey/ejc-sql/blob/a73e3c6c2865f3520b6c35df872439fd4b485d69/project.clj#L12

**Comment by kostafey** [comment]
@alf-mindshift, please, make a pull request for that.
