### ISSUE TITLE
Support for Azure SQL

### ISSUE THREAD

**Issue by alf-mindshift** [kostafey/ejc-sql#82]
Auto complete is broken when using ejc against Azure SQL. The reason is that the function [ejc-sql.structure/get-ms-sql-server-version](
https://github.com/kostafey/ejc-sql/blob/c5e43a56c983268d9360b9c0e7622c04a2f860e5/src/ejc_sql/structure.clj#L55) does not recognise the version string from Azure SQL Server, which reads  `"Microsoft SQL Azure (RTM) - 12.0.2000.8 \n\tDec 19 2018 08:43:17 \n\tCopyright (C) 2018 Microsoft Corporation\n"` at the time of writing.

**Comment by kostafey** [comment]
Fixed with Pull-request.
