### ISSUE TITLE
Replacing " with ' causes issues when playing with JSON

### ISSUE THREAD

**Issue by alf-mindshift** [kostafey/ejc-sql#94]
Running the following query (in Azure SQL Server, but other vendors have similar functionality that should suffer the same problems):

```sql
SELECT * FROM OPENJSON(N'["a"]')
```
I get: ```Error: Incorrect syntax near 'a'.```

By commenting out [ejc-interaction.el#L60](https://github.com/kostafey/ejc-sql/blob/eee730ec8f79d97f38f5a658d6ba8551326ff885/ejc-interaction.el#L60) I get the following result running the exact same query:

```
key   | 0
value | a
type  | 1
```

**Comment by kostafey** [comment]
Fixed.
